### ISSUE TITLE
Localize `Page` titles

### ISSUE THREAD

**Issue by amanbolat** [vuepressjs/vuepress-plugin-blog#16]
After generating pages for blog's title will be `Page ...` and can't be localized.

#### What problem does this feature solve?
Localization of generated pages' title.

#### How should this be implemented in your opinion?
I think we need add i18n module to add custom localization strings or be able to pass some function to change title generation process.

**Comment by newsbielt703** [comment]
I prefer adding an option `getPaginationPageTitle` to pagination config so that you'll be able to customize it just like [`getPaginationPageUrl`.](https://vuepress-plugin-blog.ulivz.com/pagination/#getpaginationpageurl)

**Comment by destinytaoer** [comment]
@newsbielt703 I also want this feature. In page 2, it shows ‘Page 1 ...’. It confuses me.

**Comment by newsbielt703** [comment]
@destinytaoer  You should open a new issue.
