### ISSUE TITLE
Generated post path gets date wrong

### ISSUE THREAD

**Issue by kastork** [vuepressjs/vuepress-plugin-blog#29]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [x] I prepared a reproduction repo, here is the reproduction repo: 
https://github.com/kastork/kirkstork.net

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?

When I make a post like `_post/2019-10-11-something.md` and then put a date front-matter like

```yaml
---
date: 2019-10-11
---
```

The generated URL will be

`/2019/10/11/something`

#### What is actually happening?

The generated URL is incorrect...

`/2019/10/10/something`

#### Other relevant information

I'm doing this on a mac and I live in the US pacific time zone.

- `npx vuepress info`:

**Comment by newsbielt703** [comment]
Thanks for report. But the reproduction seems broken. I can't even see `@vuepress/plugin-blog` in dependencies.

**Comment by kastork** [comment]
Pushed some changes, should be more useful now.

**Comment by kastork** [comment]
It looks like the system timezone affects the calculation of the path.  The Netlify CI/CD pipeline was producing the correct paths, but my local machine wasn't.

`export TZ="Etc/UTC"; vuepress build`

Produces correct results on my local machine.
