### ISSUE TITLE
Paging title

### ISSUE THREAD

**Issue by Hill-98** [vuepressjs/vuepress-plugin-blog#41]
- [ x] I confirm that this is an issue rather than a question.

## Bug report

![](https://i.loli.net/2019/12/06/WE938LQjePXqr2k.png)

This is Bug ?

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### Other relevant information

- `npx vuepress info`:

**Comment by newsbielt703** [comment]
Thanks for report. I'll fix it ASAP.
