### ISSUE TITLE
Is multi-level classification supported ???

### ISSUE THREAD

**Issue by IKangXu** [vuepressjs/vuepress-plugin-blog#43]
#### What problem does this feature solve?

Is multi-level classification supported ?

**Comment by newsbielt703** [comment]
Could you elaborate more on this? And which scenarios are this feature requested for?

**Comment by IKangXu** [comment]
@newsbielt703  If there are many classifications now, I want to group them. How can I do this??
for example
![image](https://user-images.githubusercontent.com/17905150/71648221-d8fd7b80-2d3c-11ea-9be9-9803e386d8d4.png)

**Comment by newsbielt703** [comment]
Currently, I think you can implement it with frontmatter classifier:

```js
frontmatters: [
        {
          id: "web",
          keys: ['web'],
          path: '/web/',
        },
        {
          id: "mobile",
          keys: ['mobile'],
          path: '/mobile/',
        }
      ],
```

Will it meet your needs?

**Comment by IKangXu** [comment]
@newsbielt703 
Thank you. It can't be satisfied. This configuration can't group classifications

I have realized my current requirements by combining your configuration and custom config.js

`noteConfig: {
      // 来创建左侧菜单
      nav: [
        // 通过以下方式可以获取到相应的文章内容
        // _this['$'+_this.$themeConfig.noteConfig.nav[0].frontmatter.id].map[_this.$themeConfig.noteConfig.nav[0].frontmatter.key]
        {
          text: "语言", // 左侧栏名称
          icon: "iconqq",
          frontmatter: {
            // 指定frontmatter内容
            id: "categories", // 指向vuepress-plugin-blog中的frontmatter
            key: "front" // Markdown中的frontmatter配置的categories值
          }
        },
        {
          text: "标签",
          icon: "iconqq",
          frontmatter: { id: "tags" }, // 通过这种方式进行分组设置
          items: [
            { text: "Vue", icon: "iconqq", frontmatter: { key: "Vue" } },
            { text: "Java", icon: "iconqq", frontmatter: { key: "Java" } },
            { text: "Vuepress", icon: "iconqq", frontmatter: { key: "Vuepress" } }
          ]
        }]}`

**Comment by IKangXu** [comment]
@newsbielt703 
Thank you. It can't be satisfied. This configuration can't group classifications

I have realized my current requirements by combining your configuration and custom config.js

```js
noteConfig: {
      // 来创建左侧菜单
      nav: [
        // 通过以下方式可以获取到相应的文章内容
        // _this['$'+_this.$themeConfig.noteConfig.nav[0].frontmatter.id].map[_this.$themeConfig.noteConfig.nav[0].frontmatter.key]
        {
          text: "语言", // 左侧栏名称
          icon: "iconqq",
          frontmatter: {
            // 指定frontmatter内容
            id: "categories", // 指向vuepress-plugin-blog中的frontmatter
            key: "front" // Markdown中的frontmatter配置的categories值
          }
        },
        {
          text: "标签",
          icon: "iconqq",
          frontmatter: { id: "tags" }, // 通过这种方式进行分组设置
          items: [
            { text: "Vue", icon: "iconqq", frontmatter: { key: "Vue" } },
            { text: "Java", icon: "iconqq", frontmatter: { key: "Java" } },
            { text: "Vuepress", icon: "iconqq", frontmatter: { key: "Vuepress" } }
          ]
        },
        {
          text: '目录',
          icon: 'iconqq',
          link: '', // 手动指定link优先选择
          frontmatter: { id: "tags" }, // 通过这种方式进行分组设置
          items: [
            { text: "Vue", icon: "iconqq", link: '', frontmatter: { key: "Vue" } },
            { text: "Java", icon: "iconqq", frontmatter: { key: "Java" } },
            { text: "Vuepress", icon: "iconqq", link:'', frontmatter: { key: "Vuepress" } }
          ]
        }
      ]
    }
```
