### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Himself65** [vuepressjs/vuepress-plugin-blog#44]
## Feature request

support DarkTheme

#### What does the proposed API look like?

```js
themeConfig: {
  darkTheme: {

  }
}
```

#### Are you willing to work on this yourself?

Yes

**Comment by newsbielt703** [comment]
Definitely a good idea, but it might be better if you opened this issue in [vuepress-theme-blog](https://github.com/vuepressjs/vuepress-theme-blog/issues).

**Comment by Himself65** [comment]
@newsbielt703 Thanks for the suggestion
