### ISSUE TITLE
Frontmatter classifiers' source directory

### ISSUE THREAD

**Issue by wasinator** [vuepressjs/vuepress-plugin-blog#47]
How does frontmatter classifier handle directory? 
What directory of the source markdown files does it look for? 
Can you specify the directory for each frontmatter classifier? Like in the case of internationalization.

**Comment by newsbielt703** [comment]
Please head [documentation](https://vuepress-plugin-blog.ulivz.com/guide/getting-started.html#frontmatter-classifier).
