### ISSUE TITLE
The path of the frontmatter classifier pagination page does not pick up from the config.

### ISSUE THREAD

**Issue by wasinator** [vuepressjs/vuepress-plugin-blog#48]
The path for the frontmatter classifier pagination page is fixed on '/tag/'.
For example, if the frontmatters setting on the config file goes like this:

>         frontmatters: [
>           {
>             id: "tag",
>             keys: ['tag', 'tags'],
>             path: '/blogs/tag/',
>             frontmatter: { title: 'Tag' }
>           }
>         ]

Let's say you have some blog posts with the tag 'theme'. Supposedly, the path to the page where all the posts with the tag 'theme' are listed should be '/blogs/tag/theme/'. But instead, it renders as 404 page.

While the path '/blogs/tag/' seems to render all the available tags just fine, the path '/blogs/tag/theme/' won't work. But through trial, I've noticed that this works on the path '/tag/theme/'.

**Comment by wasinator** [comment]
I think I found out that /'**tag**'/theme is fixed to the pid of the frontmatter classifier.

**Comment by newsbielt703** [comment]
@wasinator Please use the issue template.

**Comment by newsbielt703** [comment]
Which version you worked with? This was a bug fixed in V1.5.2.  

Relevant issue & PR:  #39 #40

**Comment by wasinator** [comment]
> Which version you worked with? This was a bug fixed in V1.5.2.
> 
> Relevant issue & PR: #39 #40

Mine is 1.17.3 .

**Comment by newsbielt703** [comment]
What I indicated is the version of VuePress-plugin-blog. So far, there's no 1.17.3 version.

**Comment by wasinator** [comment]
> What I indicated is the version of VuePress-plugin-blog. So far, there's no 1.17.3 version.

Sorry I looked at the wrong number. It's 1.5.1 . I'll try updating the package. Thank you for the advice.
