### ISSUE TITLE
Strange time

### ISSUE THREAD

**Issue by Hill-98** [vuepressjs/vuepress-plugin-blog#50]
- [x] I confirm that this is an issue rather than a question.

## Bug report
![1.png](https://i.loli.net/2019/12/23/k1mylQYvqFxLDZa.png)
#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

two-digit month and day

#### Other relevant information

- `npx vuepress info`:

**Comment by newsbielt703** [comment]
It's relevant to vuepress-theme-blog.

Relevant issue: [#25](https://github.com/vuepressjs/vuepress-theme-blog/issues/25)
Relevant PR: [#28](https://github.com/vuepressjs/vuepress-theme-blog/pull/28)

**Comment by Hill-98** [comment]
This is not a question of theme, it is VuePress.

See vuejs/vuepress#2097
