### ISSUE TITLE
require title keyword for frontmatters

### ISSUE THREAD

**Issue by yuchanns** [vuepressjs/vuepress-plugin-blog#52]
#### What problem does this feature solve?
give users customized title in tags page
#### What does the proposed API look like?
when people use plugin like this:
```js
plugins: [
  [
    '@vuepress/blog',
    {
      frontmatters: [
        id: 'tags',
        keys: ['tags'],
        path: '/tags/',
        layout: 'Tag',
        scopeLayout: 'Tag',
        title: '标签'
      ]
    }
  ]
]
```
then they shall see the html <title> element when visit `/tags/anyTag` like `anyTag 标签 | $siteTitle`.
#### How should this be implemented in your opinion?
Do not know

**Comment by newsbielt703** [comment]
Actually, the title is generated by `id`. Try:

```js
      frontmatters: [
        {
          id: "標籤",
          keys: ['tag'],
          path: '/tag/',
        },
      ],
```

**Comment by yuchanns** [comment]
> Actually, the title is generated by `id`. Try:
> 
> ```js
>       frontmatters: [
>         {
>           id: "標籤",
>           keys: ['tag'],
>           path: '/tag/',
>         },
>       ],
> ```

I have tried this way before the issue, and it caused another problem: I got the global computed variable like `$标签`.But what I want is that I can always use the variable as `$tags` and I am able to custom the <title> element in any language anytime without changing my code to adapt the change variable name:)
