### ISSUE TITLE
'sorter' configuration item

### ISSUE THREAD

**Issue by lhj233** [vuepressjs/vuepress-plugin-blog#60]
I want to add an article pinning feature base to the plugin. I implemented this feature by modifying the sorter configuration item, but it didn't work, although I recompiled many times.
Below is my configuration about the plugin

`[
      '@vuepress/blog',
      {
        directories: [
          {
            id: 'post',
            dirname: '_posts',
            path: '/',
            layout: 'Layout',
            itemLayout: 'Post',
            itemPermalink: '/:regular',
            pagination: {
              lengthPerPage: 5,
            },
            sorter: (prev, next) => {
              if (prev.frontmatter.sticky) return -1;
              if (next.frontmatter.sticky) return 1;
              const moment = require('moment');  
              const prevTime = moment(prev.frontmatter.date).valueOf();
              const nextTime = moment(next.frontmatter.date).valueOf();
              return prevTime - nextTime > 0 ? -1 : 1;
            }
          },
        ],
      }
    ]`

**Comment by newsbielt703** [comment]
Please follow the issue template and give the code a bit format to improve readable.

**Comment by newsbielt703** [comment]
You probably misunderstand the [config](https://vuepress-plugin-blog.ulivz.com/config/#pagination), try:

```js
directories: [
        {
          ...
          pagination:{
            sorter: (prev, next) => {
              if (prev.frontmatter.sticky) return -1;
              if (next.frontmatter.sticky) return 1;
              const dayjs = require('dayjs');
              const prevTime = dayjs(prev.frontmatter.date)
              const nextTime = dayjs(next.frontmatter.date)
              return prevTime - nextTime > 0 ? -1 : 1;
            }
          }
        },
      ],
```

**Comment by lhj233** [comment]
oops! thank you
