### ISSUE TITLE
Why is the documentation link of README.md linked to theme-blog ?

### ISSUE THREAD

**Issue by yiliang114** [vuepressjs/vuepress-plugin-blog#63]
- [ ] I confirm that this is an issue rather than a question.

#### Steps to reproduce

the documentation link of README.md is linked to `https://vuepress-theme-blog.ulivz.com` rather than `https://vuepress-plugin-blog.ulivz.com `

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [x] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?

it should be linked to  `https://vuepress-plugin-blog.ulivz.com/`

#### Other relevant information

- `npx vuepress info`:

**Comment by newsbielt703** [comment]
Thanks for the report.
