### ISSUE TITLE
404 for numeric markdown files such as 911.md

### ISSUE THREAD

**Issue by shinjawkwang** [vuepressjs/vuepress-plugin-blog#68]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [x] I prepared a reproduction repo, here is the reproduction repo: https://github.com/shinjawkwang/techArchive/tree/gh-pages

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### What is expected?
The repo is deployed by github page, and I mixed base-list-layout in @vuepress-theme-default. When accessing numeric-named pages such as /daily-coding/2020/01/23/_1927, the rendered markdown page is expected to appear.
#### What is actually happening?
The numeric-named page(/daily-coding/2020/01/23/_1927) returns 404, only at github-page deploy. This symptom doesn't appear when locally deployed or access the page by sidebar-link of theme-default at another page, whose file name is english.

#### Other relevant information

- `npx vuepress info`: Environment Info:
  System:
    OS: Linux 4.14 Ubuntu 19.04 (Disco Dingo)
    CPU: (16) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
  Binaries:
    Node: 10.18.0 - ~/.nvm/versions/node/v10.18.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.18.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v10.18.0/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @vuepress/core:  1.4.0 
    @vuepress/theme-default:  1.4.0 
    vuepress: ^1.2.0 => 1.4.0 
  npmGlobalPackages:
    vuepress: Not Found

**Comment by newsbielt703** [comment]
Sorry for the late response. 

Were you saying that files such as`/daily-config/2020-01-23-_1927.md` won't work fine? And it's only happening at gh-page deploy?

**Comment by shinjawkwang** [comment]
No, the file name is like `/daily-coding/2020-01-23-1927.md`, no `_` at filename, and it's happening on gh-page deploy.
After open issue, I found that not numeric-only file, but **numeric-starting** file doesn't work. For example, `~/2020-01-23-1023-foo/` doesn't work and `~/2020-01-23-foo-1023/` works.

**Comment by newsbielt703** [comment]
All right. It seems because Github Pages somehow doesn't support `_` prefix files.

[Solution](https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/). You can fix it by simply adding a file named `.nojekyll` in public folder.

**Comment by newsbielt703** [comment]
BTW, I should use `<router-link>` rather than  `<a>`. I found it when I checked out your repo.
```js
// docs/.vuepress/components/ListLayout.vue
<a :href="'/techArchive'+page.path">{{ page.title }}</a> // -

<router-link  :to="page.path">{{ page.title }}</router-link> // +
```

**Comment by shinjawkwang** [comment]
That works well! Thank you very much for kind explain :)
