### ISSUE TITLE
plugin package name is different with name in config file

### ISSUE THREAD

**Issue by hileon** [vuepressjs/vuepress-plugin-blog#69]
When installing with yarn or npm, this package name is `@vuepress/plugin-blog`.

During config it in vuepress, the plugin is called `@vuepress/blog`. Why are they different? Where is the plugin name `@vuepress/blog` defined?

**Comment by Kocal** [comment]
See https://vuepress.vuejs.org/plugin/using-a-plugin.html#plugin-shorthand
