### ISSUE TITLE
please show .vuepress/config.js sample format

### ISSUE THREAD

**Issue by Katheesh** [vuepressjs/vuepress-plugin-blog#73]
- [x] I confirm that this is an issue rather than a question.

#### Steps to reproduce

- [ ] I prepared a reproduction repo, here is the reproduction repo: 

- [ ] This issue doesn't need a reproduction repro, here is the steps to reproduce

#### Other relevant information

- `npx vuepress info`:

**Comment by newsbielt703** [comment]
Could you explain more about what you need?

**Comment by Katheesh** [comment]
Your sample .vuepress/confing.js file not uploaded to the repo. so we can't understand project structure. So can you upload  .vuepress/confing.js file?

**Comment by Kocal** [comment]
Everything is in [the documentation](https://vuepress-plugin-blog.ulivz.com/config/), there is even a sample config file on [the homepage](https://vuepress-plugin-blog.ulivz.com/#usage).

**Comment by newsbielt703** [comment]
In Addition, there's been an example dir in this repo. And it contains a [`.vuepress/confing.js`](https://github.com/vuepressjs/vuepress-theme-blog/blob/master/example/.vuepress/config.js) file.

**Comment by Katheesh** [comment]
> In Addition, there's been an example dir in this repo. And it contains a [`.vuepress/confing.js`](https://github.com/vuepressjs/vuepress-theme-blog/blob/master/example/.vuepress/config.js) file.

Thank you very much
